# Generated by Django 3.2.13 on 2023-10-11 06:18

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.EmailField(max_length=255, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, max_length=5, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
            managers=[
                ('objects', common.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UseService',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.userinfo')),
                ('service_code', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('industry', models.CharField(blank=True, max_length=30, null=True)),
                ('job_name', models.CharField(blank=True, max_length=10, null=True)),
                ('use_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'use_service',
                'managed': False,
            },
        ),
    ]
